[graph]
all-features = true

[advisories]
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
